name: Publish PyPi

on:
  push:
    paths:
    - 'setup.py'
    # only trigger when setup.py is changed

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      working-directory: ./gym_2048
      run: |
        python -m pytest test.py
    #tests succesful, now try to publish
    - name: Install package
      run: |
        python setup.py install
    # publish https://github.com/marketplace/actions/pypi-publish
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
      